### ISSUE TITLE
RFE: Be able to specify task timeout so that long running tasks to don't run indefinitely

### ISSUE THREAD

**Issue by Dannyb48** [ryankwilliams/blaster#30]
Hi Ryan, 

We've had a couple different teams request the capability to have Carbon tasks provide an optional parameter for timeouts so that long running tasks don't just run indefinitely. 

My thinking is that this belongs in blaster since carbon is using it as a task scheduler and queue. My initial thinking is that timeout could be a part of the task definition like so 

```
 {
            'name': 'House 1',
            'task': House,
            'methods': [
                'foundation',
                'frame',
                'roof',
                'furnish',
                'enjoy'
            ],
            'timeout': 60
            'style': 'contemporary'
        }
```
 
Wanted to see what your thoughts were and if we could collaborate on this?

**Comment by ryankwilliams** [comment]
Thanks @Dannyb48 for opening this RFE. I think this would be a nice addition to the task definition. Lets sync up on this issue after the new year!

**Comment by ryankwilliams** [comment]
Hi @Dannyb48, I have been making some modifications to simplify the code behind blaster. Previously there was two main engine classes (Parallel and Serial). I have condensed these both into one class along with some other changes. These fixes are in the master branch today. Just wanted to let you know about these and not in any version on PyPI yet.

Regarding this RFE, I put together a branch **issue-30** [1] based off the master branch. When you have sometime, feel free to test out the latest changes. I think this is what you are looking for.

Here is an example:

```python
from pprint import pprint
from time import sleep

from blaster import Blaster
from examples.house import House

if __name__ == '__main__':
    # list of tasks (houses to be built)
    tasks = [
        {
            'name': 'House 1',
            'task': House,
            'methods': [
                'foundation',
                'frame',
                'roof',
                'furnish',
                'enjoy'
            ],
            'style': 'contemporary',
            'timeout': 10
        },
        {
            'name': 'House 2',
            'task': House,
            'methods': [
                'foundation',
                'frame',
                'roof',
                'furnish',
                'post_build_tasks',
                'enjoy'
            ],
            'style': 'cape'
        },
    ]

    # create blaster object
    blast = Blaster(tasks)

    # blast off tasks in parallel
    data = blast.blastoff()

    # log results
    sleep(2)
    pprint(data, indent=4)
```

I modified the house.py example to have longer sleep:

```python
from logging import getLogger
from time import sleep


LOG = getLogger('blaster')


class House(object):
    """Build a house."""

    def __init__(self, style, **kwargs):
        """Constructor.

        :param style: Style of the house to build.
        :type style: str
        """
        self.style = style

    def foundation(self):
        """Build the foundation."""
        LOG.info('Building the foundation for %s house..' % self.style)
        sleep(1)

    def frame(self):
        """Frame the house."""
        LOG.info('Frame the house for %s house..' % self.style)
        sleep(30)

    def roof(self):
        """Roof the house."""
        LOG.info('Roof the house for %s house..' % self.style)
        sleep(1)

    def furnish(self):
        """Furnish the house."""
        LOG.info('Furnish the house for %s house..' % self.style)
        sleep(1)

    def enjoy(self):
        """Enjoy the house."""
        LOG.info('Enjoy your new %s house :)' % self.style)
        sleep(1)

    def post_build_tasks(self):
        """Post build tasks after house is built."""
        LOG.info('Perform post building tasks for %s house..' % self.style)
        sleep(1)
```

You will see the contemporary house task will timeout when trying to frame the house while the cape house example task will complete successfully since there is no timeout defined.

Output:

```
2020-01-08 16:08:13,171 INFO --> Blaster v0.2.0 <--
2020-01-08 16:08:13,171 INFO Task Execution: Concurrent
2020-01-08 16:08:13,171 INFO Tasks:
2020-01-08 16:08:13,171 INFO 1.     Task     : House 1
                                    Class    : <class 'examples.house.House'>
                                    Methods  : ['foundation', 'frame', 'roof', 'furnish', 'enjoy']
2020-01-08 16:08:13,172 INFO 2.     Task     : House 2
                                    Class    : <class 'examples.house.House'>
                                    Methods  : ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2020-01-08 16:08:13,172 INFO 3..2..1.. BLAST OFF!
2020-01-08 16:08:13,174 INFO Building the foundation for contemporary house..
2020-01-08 16:08:14,175 INFO Frame the house for contemporary house..
2020-01-08 16:08:18,184 INFO Building the foundation for cape house..
2020-01-08 16:08:19,186 INFO Frame the house for cape house..
Traceback (most recent call last):
  File "/home/rywillia/repos/blaster/blaster/engine.py", line 89, in run
    value = getattr(task_obj, method)()
  File "/home/rywillia/repos/blaster/examples/house.py", line 32, in frame
    sleep(30)
  File "/home/rywillia/repos/blaster/blaster/engine.py", line 75, in timeout_handler
    (task['name'], method))
RuntimeError: Task: House 1, method: frame, reached timeout!
2020-01-08 16:08:49,216 INFO Roof the house for cape house..
2020-01-08 16:08:50,218 INFO Furnish the house for cape house..
2020-01-08 16:08:51,219 INFO Perform post building tasks for cape house..
2020-01-08 16:08:52,220 INFO Enjoy your new cape house :)
2020-01-08 16:08:53,225 INFO BLAST OFF COMPLETE! TOTAL DURATION: 0h:0m:40s
[   {   'bid': '5ac888a0-6d55-44b1-8f2d-e662207373b0',
        'methods': [   {'name': 'foundation', 'rvalue': None, 'status': 0},
                       {   'name': 'frame',
                           'rvalue': None,
                           'status': 1,
                           'traceback': [   '  File '
                                            '"/home/rywillia/repos/blaster/blaster/engine.py", '
                                            'line 89, in run\n'
                                            '    value = getattr(task_obj, '
                                            'method)()\n',
                                            '  File '
                                            '"/home/rywillia/repos/blaster/examples/house.py", '
                                            'line 32, in frame\n'
                                            '    sleep(30)\n',
                                            '  File '
                                            '"/home/rywillia/repos/blaster/blaster/engine.py", '
                                            'line 75, in timeout_handler\n'
                                            "    (task['name'], method))\n"]}],
        'name': 'House 1',
        'status': 1,
        'style': 'contemporary',
        'task': <class 'examples.house.House'>},
    {   'bid': 'cf2b3b3e-1f14-4a5c-9936-68c4b4ebc080',
        'methods': [   {'name': 'foundation', 'rvalue': None, 'status': 0},
                       {'name': 'frame', 'rvalue': None, 'status': 0},
                       {'name': 'roof', 'rvalue': None, 'status': 0},
                       {'name': 'furnish', 'rvalue': None, 'status': 0},
                       {   'name': 'post_build_tasks',
                           'rvalue': None,
                           'status': 0},
                       {'name': 'enjoy', 'rvalue': None, 'status': 0}],
        'name': 'House 2',
        'status': 0,
        'style': 'cape',
        'task': <class 'examples.house.House'>}]

Process finished with exit code 0
```

This also works for when running tasks sequentially.

Let me know what you think.

[1] https://github.com/ryankwilliams/blaster/tree/issue-30

**Comment by ryankwilliams** [comment]
A new version of blaster is available on PyPI with this change. https://pypi.org/project/blaster/

```
[rywillia@rywillia-laptop ~]$ virtualenv blaster-0.3.0 --python /usr/bin/python3.6
Running virtualenv with interpreter /usr/bin/python3.6
Already using interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/rywillia/blaster-0.3.0/bin/python3.6
Also creating executable in /home/rywillia/blaster-0.3.0/bin/python
Installing setuptools, pip, wheel...
done.
[rywillia@rywillia-laptop ~]$ source blaster-0.3.0/bin/activate
(blaster-0.3.0) [rywillia@rywillia-laptop ~]$ pip install blaster==0.3.0
Collecting blaster==0.3.0
  Downloading blaster-0.3.0-py3-none-any.whl (26 kB)
Installing collected packages: blaster
Successfully installed blaster-0.3.0
(blaster-0.3.0) [rywillia@rywillia-laptop ~]$ pip freeze | grep blaster
blaster==0.3.0
```
